doc/specs/vulkan/appendices/extensions.txt, doc/specs/vulkan/appendices/spirvenv.txt, doc/specs/vulkan/chapters/copies.txt, doc/specs/vulkan/chapters/drawing.txt, doc/specs/vulkan/chapters/features.txt, doc/specs/vulkan/chapters/fragops.txt, doc/specs/vulkan/chapters/primsrast.txt, doc/specs/vulkan/chapters/queries.txt, doc/specs/vulkan/chapters/sparsemem.txt, doc/specs/vulkan/chapters/tessellation.txt
Submitting lots of separate pull requests is tedious, so I'll try one with lots of commits in it. If only some of the commits are acceptable, maybe they can be cherry-picked across or copied by hand or something, instead of waiting to merge the entire list.
=> Various minor fixes

src/spec/vk.xml
Kazan source: https://github.com/kazan-3d/kazan
Kazan website: http://kazan-3d.org
=> Add Kazan Software Renderer

src/ext_loader/vulkan_ext.c, src/spec/extensionStubSource.py, src/spec/genvk.py
=> include VKAPI_CALL in vulkan_ext.c functions

src/ext_loader/vulkan_ext.c, src/spec/extensionStubSource.py, src/spec/genvk.py
=> Revert "include VKAPI_CALL in vulkan_ext.c functions"

doc/specs/vulkan/chapters/drawing.txt, doc/specs/vulkan/chapters/pipelines.txt
=> Fix vkCmdDraw*AMD text bugs

doc/specs/vulkan/Makefile, doc/specs/vulkan/appendices/VK_AMD_gpu_shader_int16.txt, doc/specs/vulkan/appendices/VK_AMD_shader_image_load_store_lod.txt, doc/specs/vulkan/appendices/VK_AMD_texture_gather_bias_lod.txt, doc/specs/vulkan/appendices/VK_EXT_shader_stencil_export.txt, doc/specs/vulkan/appendices/VK_KHR_maintenance2.txt, doc/specs/vulkan/appendices/VK_NN_vi_surface.txt, doc/specs/vulkan/chapters/VK_KHR_surface/wsi.txt
^
Update some dates to conform to ISO 8601
exported from #600.
=> Update some old date formats

doc/specs/vulkan/appendices/VK_AMD_shader_fragment_mask.txt, doc/specs/vulkan/appendices/spirvenv.txt, doc/specs/vulkan/chapters/features.txt, doc/specs/vulkan/chapters/interfaces.txt, doc/specs/vulkan/chapters/introduction.txt, doc/specs/vulkan/chapters/tessellation.txt, doc/specs/vulkan/chapters/textures.txt
Fix some broken links.
Ex #600
=> Fix broken links

doc/specs/vulkan/chapters/VK_KHR_android_surface/platformCreateSurface_android.txt, doc/specs/vulkan/chapters/features.txt, doc/specs/vulkan/chapters/resources.txt, doc/specs/vulkan/chapters/shaders.txt
=> Fix Note markup

src/spec/validitygenerator.py
=> Make all queue names starting with capital

doc/specs/vulkan/appendices/VK_EXT_discard_rectangles.txt, doc/specs/vulkan/appendices/VK_EXT_display_control.txt, doc/specs/vulkan/appendices/VK_EXT_swapchain_colorspace.txt, doc/specs/vulkan/appendices/VK_KHR_bind_memory2.txt, doc/specs/vulkan/appendices/VK_KHR_swapchain.txt, doc/specs/vulkan/appendices/VK_NV_clip_space_w_scaling.txt, doc/specs/vulkan/appendices/VK_NV_framebuffer_mixed_samples.txt, doc/specs/vulkan/appendices/VK_NV_geometry_shader_passthrough.txt, doc/specs/vulkan/appendices/VK_NV_viewport_swizzle.txt, doc/specs/vulkan/appendices/boilerplate.txt, doc/specs/vulkan/appendices/glossary.txt, doc/specs/vulkan/chapters/VK_EXT_hdr_metadata.txt, doc/specs/vulkan/chapters/VK_KHR_display/display.txt, doc/specs/vulkan/chapters/cmdbuffers.txt, doc/specs/vulkan/chapters/extensions.txt, doc/specs/vulkan/chapters/fundamentals.txt, doc/specs/vulkan/chapters/fxvertex.txt, doc/specs/vulkan/chapters/initialization.txt, doc/specs/vulkan/chapters/interfaces.txt, doc/specs/vulkan/chapters/introduction.txt, doc/specs/vulkan/chapters/renderpass.txt, doc/specs/vulkan/chapters/resources.txt, doc/specs/vulkan/chapters/samplers.txt, doc/specs/vulkan/chapters/sparsemem.txt, doc/specs/vulkan/chapters/vertexpostproc.txt
=> Fix some quotes and apostrophes

doc/specs/vulkan/chapters/descriptorsets.txt
=> Fix text block in descriptor sets ch.

doc/specs/vulkan/appendices/VK_KHR_display.txt, doc/specs/vulkan/appendices/VK_KHR_external_semaphore.txt, doc/specs/vulkan/chapters/VK_KHR_swapchain/wsi.txt, doc/specs/vulkan/chapters/cmdbuffers.txt
- 2x improper use per Terminology
- 2x just grammar
=> Fix "can not"

chapters/copies.txt, chapters/descriptorsets.txt
Fixed some duplicate words and some spellings of "stages" as "stagess".
=> Fixed small typos

chapters/VK_EXT_debug_utils.txt, chapters/VK_GOOGLE_display_timing/queries.txt, chapters/VK_NN_vi_surface/platformCreateSurface_vi.txt, chapters/VK_NVX_device_generated_commands/generatedcommands.txt, chapters/VK_NVX_device_generated_commands/indirectcommands.txt, chapters/VK_NVX_device_generated_commands/objecttable.txt, chapters/cmdbuffers.txt, chapters/copies.txt, chapters/descriptorsets.txt, chapters/drawing.txt, chapters/extensions.txt, chapters/features.txt, chapters/fxvertex.txt, chapters/initialization.txt, chapters/memory.txt, chapters/renderpass.txt, chapters/resources.txt, chapters/synchronization.txt
Change occurrences of "is an Vk*" to "is a Vk*"
=> Fix small typos

xml/extensionmetadocgenerator.py
- add GitHub and GitLab logos
- point GitHub contacts to prefilled New Issue
=> Pretty contacts in extension appendices

xml/vk.xml
=> Make vkQueueWaitIdle externsync

.gitlab/issue_templates/Release checklist.md, COPYING.md, ChangeLog.txt, appendices/VK_KHR_maintenance2.txt, chapters/copies.txt, chapters/dispatch.txt, chapters/drawing.txt, chapters/shaders.txt, chapters/synchronization.txt, style/markup.txt, style/writing.txt
As the title says, this just fixes a handful of repeated words.
=> Fixed repeated words

chapters/VK_NVX_raytracing/raytracing.txt, chapters/pipelines.txt, chapters/primsrast.txt
- remove `{fullimagewidth}` (not sure what it is, but it does not seem to exist)
- add missing `{imageopts}`
=> Fix bad figures options

appendices/boilerplate.txt, chapters/features.txt, chapters/primsrast.txt, config/attribs.txt
Prevents showing slider (tested on 16:10 display), but still many things extends into the bounds (probably ok enough).
=> Try to fix html page overflow

appendices/VK_AMD_shader_info.txt
=> Add missing VkShaderResourceUsageAMD to extension appendix

chapters/interfaces.txt
also PR #731 requires to only the Note icon be used...
=> Make WARNING into NOTE (per styleguide)

appendices/memorymodel.txt
Add acyclicity (consistency) axiom and rephrase Scoped Modification Order Coherence section as a consequence of it.
For https://github.com/KhronosGroup/Vulkan-MemoryModel/issues/13
=> Memory Model: Add acyclicity (consistency) axiom

chapters/samplers.txt
- Remove bunch of `unnormalizedCoordinates` stuff that is already VU
- Fix formatting of shader related  `unnormalizedCoordinates`
restrictions
=> Remove sampler descriptions already in VU

xml/vk.xml
=> Reserve extension 286 for wl_acquire_display

chapters/initialization.txt
=> Clarify fptr get tables

chapters/VK_KHR_swapchain/wsi.txt
=> Rename pixel shaders to fragment shaders

appendices/VK_KHR_surface.txt
=> Fix VK_KHR_surface issue 2

chapters/VK_KHR_surface/wsi.txt
=> Clarify surface queries intro paragraph

chapters/synchronization.txt
=> Fix colloquial "release memory barrier"

chapters/synchronization.txt
=> Editing of Events description paragraph

chapters/VK_KHR_swapchain/wsi.txt
fix #1191
@stonesthrow pls review
=> Add note about WSI origin location

chapters/VK_NV_ray_tracing/raytracing-resources.txt, chapters/VK_NV_ray_tracing/raytracing.txt, chapters/clears.txt, chapters/commonvalidity/build_acceleration_structure_common.txt, chapters/limits.txt, scripts/spec_tools/validity.py, xml/vk.xml
Some overlap with #1215 (sorry).
=> Fix C arrow markup

chapters/initialization.txt
=> Move vkEnumerateInstanceVersion note before VU

chapters/VK_EXT_debug_utils.txt, chapters/VK_EXT_headless_surface/headless.txt, chapters/VK_EXT_metal_surface/platformCreateSurface_metal.txt, chapters/VK_FUCHSIA_imagepipe_surface/platformCreateSurface_imagepipe.txt, chapters/VK_GGP_stream_descriptor_surface/platformCreateSurface_streamdescriptor.txt, chapters/VK_KHR_android_surface/platformCreateSurface_android.txt, chapters/VK_KHR_wayland_surface/platformCreateSurface_wayland.txt, chapters/VK_KHR_xcb_surface/platformCreateSurface_xcb.txt, chapters/VK_KHR_xlib_surface/platformCreateSurface_xlib.txt, chapters/VK_MVK_ios_surface/platformCreateSurface_ios.txt, chapters/VK_MVK_macos_surface/platformCreateSurface_macos.txt, chapters/VK_NN_vi_surface/platformCreateSurface_vi.txt
=> Add reserved bitmask types to spec

chapters/fragops.txt, chapters/pipelines.txt, chapters/primsrast.txt, xml/vk.xml
fix #1180 
fix #1267 
Some overlap from #1185 which is non-trivial to rebase
=> Add dynamic state VUs at proper place

xml/vk.xml
=> Use unsigned integers to perform bitwise operations

Makefile, scripts/translate_math.js
- move `translate_math.js` to `scripts`
- cleanup in Makefile to complement it
- add script file header
=> Move katex script to proper dir

xml/vk.xml
See https://github.com/KhronosGroup/Vulkan-Docs/pull/1292
Nicolas Caramelli
=> Reserve extension 347 for VK_EXT_directfb_surface

chapters/textures.txt
=> Fix linear filtering equation block

chapters/renderpass.txt, xml/vk.xml
=> Remove VkRenderPassCreateFlags from extension

xml/vk.xml
References: https://github.com/KhronosGroup/Vulkan-Docs/issues/1354
=> Reserve extension 354 for VK_EXT_physical_device_drm

xml/vk.xml
Hi,
A couple of months ago I asked about possibility to add the new platform extension to add support for QNX. I went through the legal jungle and now we ready to sign CLA. I will submit all further changes using this corporate account.
Here is a small initial PR to claim the extension number and add the new vendor.
Thanks,
=> Claim the extension number and add the new vendor.

xml/vk.xml
constent -> constant (in 2 comments)
=> spelling fix

chapters/VK_KHR_swapchain/wsi.txt
Migration from https://github.com/alexanderguyer/Vulkan-Docs/pull/1
This pull request aims to resolve #1419
=> Update to WSI Swapchain chapter regarding "release" and "present" terminology

chapters/VK_AMD_buffer_marker/copies.txt, chapters/VK_NV_device_generated_commands/indirectcommands.txt, chapters/queries.txt, chapters/synchronization.txt
=> Correct stage parameter names

chapters/devsandqueues.txt, chapters/fundamentals.txt, chapters/introduction.txt
=> Split errors chapter

xml/vk.xml
This was missing from my previous PR #1514.
=> Add another missing optional

appendices/VK_EXT_physical_device_drm.txt, chapters/devsandqueues.txt, xml/vk.xml
Closes: https://github.com/KhronosGroup/Vulkan-Docs/issues/1354
=> Add specification for VK_EXT_physical_device_drm

xml/vk.xml
=> Add a new driver id VK_DRIVER_ID_MESA_VENUS

chapters/descriptorsets.txt
=> Improved wording of vkCmdBindDescriptorSets

proposals/VK_EXT_graphics_pipeline_library.asciidoc
This PR fixes two minor mistakes in the vertex shader sample for the VK_EXT_graphics_pipeline_library proposal.
=> Minor fix for VK_EXT_graphics_pipeline_library proposal vertex shader sample code

chapters/fundamentals.txt
=> Fix typos in typo alias example

xml/vk.xml
Fixes #1830.
I only edited the vk.xml, I don't know if there's any other steps I need to take.
=> Add VK_KHR_depth_stencil_resolve dependency to VK_KHR_dynamic_rendering

chapters/pipelines.txt
=> Remove duplicate valid usage statement 06060

chapters/cmdbuffers.txt, chapters/commonvalidity/bind_image_common.txt, chapters/commonvalidity/draw_dispatch_common.txt, chapters/commonvalidity/draw_indirect_drawcount.txt, chapters/commonvalidity/query_begin_common.txt, chapters/commonvalidity/stage_mask_2_common.txt, chapters/commonvalidity/stage_mask_common.txt, chapters/devsandqueues.txt, chapters/features.txt, chapters/fragops.txt, chapters/framebuffer.txt, chapters/fundamentals.txt, chapters/memory.txt, chapters/pipelines.txt, chapters/primsrast.txt, chapters/queries.txt, chapters/resources.txt, chapters/samplers.txt, chapters/sparsemem.txt, chapters/vertexpostproc.txt, style/writing.txt
closes https://github.com/KhronosGroup/Vulkan-Docs/issues/1889
=> reference features by feature name

chapters/commonvalidity/draw_indexed_common.adoc, chapters/drawing.adoc
closes https://github.com/KhronosGroup/Vulkan-Docs/issues/1924
=> Add Index Buffer Bound VUID

appendices/versions.adoc
closes https://github.com/KhronosGroup/Vulkan-Docs/issues/1948
=> Add note about ShaderViewportIndexLayerEXT being split up

chapters/limits.adoc
=> Fix ```maxPushDescriptors``` description

scripts/doctransformer.py, scripts/reflow-tests/.gitignore, scripts/reflow-tests/expect-ifdef-in-vu.adoc, scripts/reflow-tests/expect-new-vuid.adoc, scripts/reflow-tests/expect-table.adoc, scripts/reflow-tests/expect-text.adoc, scripts/reflow-tests/expect-vu.adoc, scripts/reflow-tests/expect-vuid-repeat.adoc, scripts/reflow-tests/src-ifdef-in-vu.adoc, scripts/reflow-tests/src-new-vuid.adoc, scripts/reflow-tests/src-table.adoc, scripts/reflow-tests/src-text.adoc, scripts/reflow-tests/src-vu.adoc, scripts/reflow-tests/src-vuid-repeat.adoc, scripts/reflow.py, scripts/test_reflow.py
The reflow code traversed asciidoc files and modified them.  The logic to traverse the files is split into its own class for future reuse.
=> Separate reflow doc traversal and logic

registry.adoc
=> Specify operator precedence in XML `depends` expressions

.github/workflows/CI.yml
=> Update Vulkan-Hpp CI steps and add CTS framework test

chapters/cmdbuffers.adoc
=> Fix markup typo

xml/vk.xml
=> Add MSFT tag and reserve an extension number

chapters/resources.adoc
change `VkAccelerationStructureCreateInfoKHR::flags` to `VkAccelerationStructureCreateInfoKHR::createFlags`
=> VkAccelerationStructureCreateInfoKHR flags to createFlags

chapters/cmdbuffers.adoc, chapters/resources.adoc, chapters/synchronization.adoc
mostly for better fulltext searchability
=> Use proper\full QFOT name

BUILD.adoc, appendices/VK_QCOM_image_processing.adoc, appendices/VK_QCOM_image_processing2.adoc, appendices/VK_QCOM_multiview_per_view_viewports.adoc, appendices/VK_QCOM_render_pass_transform.adoc, chapters/VK_NV_low_latency2/low_latency2.adoc, chapters/accelstructures.adoc, chapters/capabilities.adoc, chapters/interfaces.adoc, chapters/memory.adoc, chapters/primsrast.adoc, chapters/renderpass.adoc, chapters/shaders.adoc, chapters/textures.adoc, chapters/video/encode.adoc, proposals/VK_KHR_maintenance5.adoc, proposals/VK_QCOM_image_processing.adoc, scripts/doctransformer.py, style/extensions.adoc
=> Resolve some typos

chapters/renderpass.adoc
=> Update refpage short descriptions of VkAttachmentLoad/StoreOp to be consistent with spec language

xml/vk.xml
Per #2410, this reserves extension number 604.
=> Reserve extension #604

chapters/synchronization.adoc
Pull request associated with issue #2412 .
=> minor wording change to avoid ambiguity in 'the act of waiting'.

xml/vk.xml
This is the final GitHub rename, I promise ;-)
I'm standardizing my usernames across the web to be @linyaa when available, and otherwise match regex /linyaa[._-]?kiwi/, depending on which chars the site allows.
=> Rename Lina's GitHub username to @linyaa-kiwi

proposals/VK_EXT_device_generated_commands.adoc
This PR fixes minor issues I found while following the proposal for VK_EXT_device_generated_commands.
P.S. : Both the extension doc and the proposal still have a "todo" in their examples section.
=> Fix some issues with VK_EXT_device_generated_commands proposal

chapters/VK_KHR_surface/wsi.adoc
Same type of changes for other files I also want to include in this PR, if this one is OK.
=> Match pname with vk.xml.

.github/workflows/CI.yml
There's a permission issue I don't fully understand but this appears to be a workaround.
=> Try to make git commands from CI actions work
