doc/specs/vulkan/chapters/drawing.txt
Fixed a naming error in the documentation in order not to repeat the same function name
=> drawing.txt: fix function name. fixes #11

doc/specs/vulkan/chapters/primsrast.txt
Fixed a naming error in the documentation to match vulkan.h
=> primsrast.txt: fix variable name. fixes #8

doc/specs/vulkan/man/vkCmdDraw.txt
Fixed a typo in the specification
=> vkCmdDraw.txt: fix typo

src/spec/vk.xml
There is no pSubresource, srcSubresource, dstSubresource;
only imageSubresource.
=> VkBufferImageCopy: Fix references to subresources

doc/specs/vulkan/validity/protos/vkCmdCopyBuffer.txt
The member is just called 'size'.
=> vkCmdCopyBuffer: Fix references to copySize

doc/specs/vulkan/chapters/copies.txt
These look like copy-paste errors from vkCmdBlitImage into vkCmdResolveImage.
=> vkCmdResolveImage: Fix references to blitting

doc/specs/vulkan/chapters/features.txt
See #102 which fixed one latexmath: macro problem and in doing so exposed another one that had been lurking.
=> [ChangeLog] Build fix for latexmath: without escaped right brackets in the features section.

doc/specs/vulkan/appendices/extensions.txt, doc/specs/vulkan/chapters/devsandqueues.txt, doc/specs/vulkan/chapters/extensions.txt, doc/specs/vulkan/chapters/features.txt, doc/specs/vulkan/chapters/initialization.txt, doc/specs/vulkan/chapters/interfaces.txt, doc/specs/vulkan/chapters/memory.txt, doc/specs/vulkan/chapters/primsrast.txt, doc/specs/vulkan/chapters/vertexpostproc.txt, doc/specs/vulkan/enums/VkCullModeFlagBits.txt, doc/specs/vulkan/enums/VkStencilFaceFlagBits.txt, doc/specs/vulkan/style/styleguide.txt, doc/specs/vulkan/validity/protos/vkCmdCopyBuffer.txt, doc/specs/vulkan/validity/protos/vkEnumerateDeviceExtensionProperties.txt, doc/specs/vulkan/validity/protos/vkEnumerateInstanceExtensionProperties.txt, doc/specs/vulkan/validity/structs/VkBufferImageCopy.txt, doc/specs/vulkan/validity/structs/VkPipelineMultisampleStateCreateInfo.txt, doc/specs/vulkan/validity/structs/VkPipelineRasterizationStateCreateInfo.txt, src/spec/vk.xml, src/vulkan/vulkan.h
This is for people to review edits for @philiptaylor's points in #101, but I'll probably pull equivalent changes back into the private repo and merge there before bringing it back to github in one of the (hopefully) weekly updates.
[ChangeLog] This bundles up low-hanging editorial issues from public issue
101. Some items from that issue are more complex and remain to be done.
There's also some related cleanup of the extensions appendix to clarify the
distinction between a Vulkan API command, and the functions and function
pointers corresponding to that command which may be provided by the API
loader and runtime.                                 
Remaining todo:
=> Fixes for #101 (public issue 101)

src/spec/registry.rnc, src/spec/validitygenerator.py
- fix `latex:` used in validity for remaining comma separated lengths in `len`
- correct comments in `registry.rnc` also refering to `latex:`
fixes rest of the emergent issue in #555
=> Fix remaining len latexmath confusion

doc/specs/vulkan/chapters/descriptorsets.txt, src/spec/validitygenerator.py, src/spec/vk.xml
- Make implicit validity for optional `void*` mean "nothing" in the
script
- Make `optional` mean non-NULL for `void*` in the registry (unimplemented in script though; there is not much use for non-optional void*)
- Uses of `void*` that point to something should preferrably have `noautovalidity`
(adding it)
- Add missing explicit VUs of `void*` parameters
(`vkCmdPushDescriptorSetWithTemplateKHR` and
`vkUpdateDescriptorSetWithTemplateKHR`)
- Also indirectly fixes `vkMapMemory`, `VkAllocationCallbacks`,
`VkDebugReportCallbackCreateInfoEXT`, and Apple and NN surface creation
- Remove ugly text hack from script
=> Tweak some void* (auto)validity

src/spec/validitygenerator.py, src/spec/vk.xml
Previously it required to be valid combination + non-0
(for `vkGetDeviceGroupSurfacePresentModesKHX::pModes` and`vkGetDeviceGroupPeerMemoryFeaturesKHX::pPeerMemoryFeatures`)
exported from #547 (was bit offtopic there and now allows better piecemeal reviewing)
=> Fix autovalidity for output Flags pointers

doc/specs/vulkan/registry.txt, src/spec/registry.rnc, src/spec/vk.xml
1) Fix `pSampleMask `s `altlen` to have C99 semantics equivalent to len
2) Fix `registry.rnc` to also have altlen for `param`s
3) Document `altlen` in `registry.rnc` comments
4) Clarify `altlen` in schema doc that beside C syntax it also follows C semantics
5) Clarify `altlen` in schema doc in case there ever is `latexmath` in
comma separated `len`
I am impartial to nr. 4, it could as well follow "infinite precission math" semantics. 
(TBH there are only two `len` latexmath attributes. Might as well hard-code it into a parser and update it once in a decade when new latexmath appears. And these cases could even be `noautovalidity` instead of polluting xml with latex.)
But either way (or especially if it does not have C semantics) it has to be documented.
=> Fix and clarify altlen

doc/specs/vulkan/chapters/synchronization.txt
The specification calls it VK_DEVICE_LOST in several places.
=> Fix references to VK_ERROR_DEVICE_LOST

doc/specs/vulkan/Makefile, doc/specs/vulkan/config/themes/pdf-theme.yml
Adding chapter name into the pdf page footer.
Fixes #2 
The used theme is the [default theme from Asciidoctor master](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/data/themes/default-theme.yml) with only change to the footer.
=> Adding chapter name into the pdf page footer

doc/specs/vulkan/chapters/primsrast.txt
This is probably a small mistake in the specs, since `minSampleShading` is not a bool but a float.
=> Fix wrong param name in PipelineMultisampleStateCreateInfo validity

doc/specs/vulkan/chapters/VK_KHR_swapchain/wsi.txt
- fix `pretransform` and `compositeAlpha`; they are values not bitmasks
- update `imageFormat`, `imageColorSpace`, `imageUsage`  and `oldSwapchain` to be specific to behavior of this command
- fix broken unintended code block
- move `VK_TRUE` clipping text to correct bullet point
- rewrite Note to (hopefully) help clarity and brevity
- random tweaks...
=> Update VkSwapchainCreateInfoKHR descriptions

doc/specs/vulkan/chapters/clears.txt, doc/specs/vulkan/chapters/copies.txt, doc/specs/vulkan/chapters/resources.txt, doc/specs/vulkan/chapters/sparsemem.txt, doc/specs/vulkan/chapters/synchronization.txt
- fixes rest of #416 (`VkImageSubresourceLayers`)
- migrate `VkImageSubresource` VUs where the state is known
- Simplify `VkImageSubresource`  (`*count` should always > 0)
=> Fix VkImageSubresource* VUs

doc/specs/vulkan/chapters/VK_KHR_swapchain/wsi.txt, doc/specs/vulkan/chapters/cmdbuffers.txt, doc/specs/vulkan/chapters/descriptorsets.txt, doc/specs/vulkan/chapters/fragops.txt, doc/specs/vulkan/chapters/fundamentals.txt, doc/specs/vulkan/chapters/memory.txt, doc/specs/vulkan/chapters/pipelines.txt, doc/specs/vulkan/chapters/renderpass.txt, doc/specs/vulkan/chapters/resources.txt, doc/specs/vulkan/chapters/vertexpostproc.txt, src/spec/validitygenerator.py
1) State more explicitly in VUs if "valid" pointer is required
It is bit unnecessary for VU statements that say "point to a valid". But is more clear for statements that say e.g. "`pInstance` **must** be a pointer to a `VkInstance` handle" (which, literaly, it is by definition &mdash; that's the static type of the pointer)
2) Implicit validity is quite explicit for some time. Update pointer section as such.
3) Sometimes pointer parameter can be ignored. Update implicit pointer validity section as such.
4) Changing to more forceful language, to clarify pointers need synchronizing too, which is similar to "externally synchronized" objects.
=> Clarify pointer autovalidity and threading

doc/specs/vulkan/appendices/VK_EXT_blend_operation_advanced.txt, doc/specs/vulkan/appendices/VK_NV_clip_space_w_scaling.txt, doc/specs/vulkan/appendices/VK_NV_viewport_swizzle.txt, doc/specs/vulkan/chapters/VK_KHR_surface/wsi.txt, doc/specs/vulkan/chapters/copies.txt, doc/specs/vulkan/chapters/descriptorsets.txt, doc/specs/vulkan/chapters/features.txt, doc/specs/vulkan/chapters/interfaces.txt, doc/specs/vulkan/chapters/textures.txt
incl. two unparsable latexmath blocks
exported from #600 
PS: It would be nice to note in styleguide how to do a block equation using the [eq]. (Make it just separate paragraph? Or envelop it in something?)
PS2: Variables in `[eq]` should probably be italicized to match latexmath. Also worth noting in styleguide...
=> Fix random math markup

doc/specs/vulkan/appendices/VK_EXT_debug_marker.txt
Example 1 of the VK_EXT_debug_marker specification was erroneously using a VkDeviceCreateInfo structure instead of VkDebugMarkerObjectNameInfoEXT  to set the debug object name for the image.
=> VkDebugMarkerObjectNameInfoEXT instead of VkDeviceCreateInfo

doc/specs/vulkan/chapters/fragops.txt
- remove redundant VU about the `pDiscardRectanges` vector; it is implicit
- remove redundant VU about `firstDiscardRectangle` it is fully covered by `00585` and implicit VU that says `discardRectangleCount` >0
- remove redundant VU part saying &ge;1; it is implicit because of `discardRectangleCount` > 0
- tweak `VkRect2D` VUs to mention the array they are part of
=> Remove redundant vkCmdSetDiscardRectangleEXT VUs + tweaks

doc/specs/vulkan/chapters/VK_KHR_swapchain/wsi.txt
Add to `vkAcquireNextImageKHR` and `VkAcquireNextImageInfoKHX` VUs:
- semaphore must not have pending ops
- app must use semaphore and/or fence
=> Add synchronization VUs to vkAcquireNextImage

doc/specs/vulkan/chapters/vertexpostproc.txt
- fixes #622 
- fixes #584 
Should really say something like:
> - If `VK_KHR_maintenance1` or `VK_AMD_negative_viewport_height` is not enabled `height` **must** be greater than `0.0`
> - If `VK_EXT_depth_range_unrestricted` is not enabled `minDepth` **must** be between `0.0` and `1.0`, inclusive
but that's more of a systemic spec problem (#533)...
=> Clean up VkViewport VU section

doc/specs/vulkan/appendices/VK_IMG_filter_cubic.txt, doc/specs/vulkan/chapters/VK_IMG_filter_cubic/filter_cubic_sampled_bit_description.txt
- correct ul below `VkFormatFeatureFlagBits`
- document in extension appendix
=> Fix CUBIC feature flag documentation

doc/specs/vulkan/chapters/VK_NV_clip_space_w_scaling/vertexpostproc.txt, doc/specs/vulkan/chapters/vertexpostproc.txt, src/spec/vk.xml
- make implicit for `vkCmdSetViewport`
- make implicit for `vkCmdSetViewportWScalingNV`
- <s>removed redundant explicit duplicate for `vkCmdSetDiscardRectangleEXT`</s>
Not sure why they were `noautovalidity`. Possibly because the script forgets to add "valid" (some kind of bug)?
=> Make dynamic state array len VU implicit

doc/specs/vulkan/chapters/VK_KHR_swapchain/wsi.txt
Remove duplicate present layout note.
The identical thing is already below `VkPresentInfoKHR` where it belongs.
=> Remove duplicate present layout note

doc/specs/vulkan/chapters/features.txt
When this enum was renamed, this must have been overlooked.
=> Fix typo: Change 'FENCE_FD' to 'SYNC_FD'

chapters/VK_KHR_swapchain/wsi.txt
- make **must** statement a proper VU
- fix sentence saying only one swapchain can be associated
- fix languge saying **must** not instead of **cannot**
- clarify all the cases when swapcahin cannot be created
- fixes #438
=> Refine swapchain association with surface

appendices/glossary.txt, chapters/extensions.txt
- requires impls to honor resolution in #659
- addresses some confusion in https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2366
- require impls to support dependencies
=> Refine extension dependencies

chapters/resources.txt
- previously VU exluded if `1.1` or `VK_KHR_device_group`, but if swapchain ext. not defined memory param should be valid too
=> now excluded iff `VK_KHR_swapchain` is defined too.
`(1.1 or VK_KHR_device_group) and VK_KHR_swapchain` should show swapchain specific VU (which provides memory through `pNext` instead). Negative of that should show the core VU ("`memory` must be valid").
=> Correct mem VU ifdef scope in VkBindImageMemoryInfo 

xml/reg.py
With the addition of the 'extnumber' key update comparison to skip over
the extnumber as well as extname in order to avoid a bunch of
irrelevant warnings.
=> scripts:Account for extnumber key to fix warnings

appendices/VK_ANDROID_external_memory_android_hardware_buffer.txt, chapters/clears.txt, chapters/copies.txt, chapters/dispatch.txt, chapters/drawing.txt, chapters/features.txt, chapters/memory.txt, chapters/resources.txt
Reapply #698 (with a revenge), which seems to have been reverted by 1.1.75.
=> Reapply #698: VK_ANDROID_external_memory_android_hardware_buffer markup cleanup

chapters/descriptorsets.txt
There's a paragraph under VkImageSubresourceRange description that
contains this restriction but no VU under the vkUpdateDescriptors()
section. Adding the VU for clarity as the existing paragraph is easy
to miss.
=> Add VU for depth/stencil image descriptor

chapters/renderpass.txt, chapters/synchronization.txt
Fix VkSubpassDependency self-dependency stage VU
- Fix `ifdef` inside VU entry, which e.g. breaks the `validusage.json`.
- Allow multiple stage bits to be set, not just one. (Other VUs seem to expect multiple bits, and there's no reason to ban it I think).
=> Fix VkSubpassDependency self-dependency stage VU

chapters/VK_KHR_display/display.txt, chapters/clears.txt, chapters/copies.txt, chapters/pipelines.txt, registry.txt, xml/validitygenerator.py, xml/vk.xml
- update script to detect better structs that do not need "valid"
- update `vk.xml` and schema to say `noautovalidity` as a hint to the script
- fix missing `const` in `VkValidationFlagsEXT`
- update some cases that were probably avoiding the bug
complements changes in PR #589
=> Fix missing "valid" in some obscure cases

xml/vk.xml
`-12` is actually used, and the tag does not seem to be useful for anything...
=> Delete wrong <unused> tag

chapters/cmdbuffers.txt, chapters/drawing.txt, chapters/pipelines.txt, chapters/primsrast.txt, chapters/sparsemem.txt, chapters/tessellation.txt, chapters/textures.txt
This inlines `<svg>` elements in the HTML, instead of using `<img>` tags with `src="data:..."`.
Provides a 12.6% size savings for vkspec.html
(697770 B -> 609679 B, when served gzipped, as on khronos.org), because:
1. plaintext is smaller than base64-encoded plaintext, and
2. base64 does not gzip as well as plaintext SVG.
Documentation on `[%inline]` can be found here:
https://github.com/asciidoctor/asciidoctor-bespoke#inserting-svgs
=> Use [%inline] for all SVGs

xml/extensionmetadocgenerator.py
mostly added comments
`doc += content` -> `doc += innerdoc ` does the fix
=> Fix metadoc script showing non-selected extensions

chapters/synchronization.txt
` VK_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT` has to be defined as part of graphics pipeline in order for VU modified in #742 to be accurate
=> Reapply #742:  Make STAGE_CONDITIONAL_RENDERING part of graphics pipe

xml/vk.xml
comma is a separator and cannot be within single contact item
=> Fix contacts split with comma

xml/vk.xml
This wording appears to refer to the conditions under which e.g. the `pBufferInfo` member of `VkWriteDescriptorSet` is not ignored, rather than the field in question, which to my reading must always be set to a valid buffer in a non-ignored `VkDescriptorBufferInfo`.
CC @krOoze
=> Remove misleading wording in VkDescriptorBufferInfo::buffer comment

chapters/textures.txt
Merge this branch if the sRGB conversion is enabled based on the **image view** format, and not based on the **image** format.
=> sRGB enabled based on image view format

xml/extensionmetadocgenerator.py
Fixes:
>asciidoctor: WARNING: image to embed not found or not readable: /mnt/c/Dev/_GitHub/Vulkan-Docs/%20&amp;body=@alonorbach%20+
=> Fix special characters in GitHub contacts links (fix PR #770)

chapters/primsrast.txt
A small typo. PTAL. 
For your convenience, you can find out the text by search "Note that t = 0" at the latest Vulkan spec (1.1.83): https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html.
=> Fix a small typo in chapter 24.6.1: Basic Line Segment Rasterization

appendices/VK_KHR_create_renderpass2.txt
The appendix for VK_KHR_create_renderpass2 now points explicitly at structures and parameters mapped into the new extension.
Addresses https://github.com/KhronosGroup/Vulkan-Docs/issues/736#issuecomment-403218142
=> Better specify parameter mapping for VK_KHR_create_renderpass2 

chapters/VK_EXT_debug_utils.txt, xml/vk.xml
fixes #788 
Decided to change the name of the callback parameter in the XML. The name of a parameter should not matter in a function pointer, I think.
=> Fix #788: make clear messageTypes is a bitmask + name fix

xml/genvk.py
Python 3.8 will remove the "time.clock()" option we currently use.
Instead, we should "time.process_time()".
=> Fix python 3.7 warning

BUILD.adoc
Update/simplify Ubuntu subsystem build instructions.
Resetting my environment, I did not encounter any gem compatibility problems currently, and did not need `rbenv` nor `rvm` at all.
`MATHEMATICAL_SKIP_STRDUP` does not seem to be needed anymore in new versions.
Did mot find what `gtk-doc-tools` is used for. Things seem to work without it.
=> Update Ubuntu subsystem build instructions

chapters/VK_EXT_debug_utils.txt, xml/vk.xml
Fixing a few items discovered by @krOoze with the EXT_debug_utils
extension spec language validation.  Namely in two issues:
Issue #789:
The problem was the manual VUs should have been applied to
the `vkSetDebugUtilsObjectNameEXT` command and not the
general `VkDebugUtilsObjectNameInfoEXT` structure.
Issue #790:
Here, we needed to remove the "noautovalidity" tag on
the XML and add the "optional" tag to `pObjects` and
`objectCount`.
=> debug_utils: Fix issues discovered by @krOoze

config/optimize-pdf
fixes #877 
Not quite sure what the flag is supposed to be doing. Based on https://bugs.ghostscript.com/show_bug.cgi?id=699830.
Alternatively downgrade ghostscript to <= 9.23.
=> Fix links in PDF build

xml/vk.xml
`VkPhysicalDeviceProperties` does not have a `pNext` member.
=> Fix typo in VkPhysicalDeviceShadingRateImagePropertiesNV structextends

xml/genvk.py
In Python2, the script would not be able to use the `time` argument, but would otherwise work as expected.
Needed for ANGLE.
=> Make genvk.py work in Python2

appendices/memorymodel.txt
Fixes https://github.com/KhronosGroup/Vulkan-MemoryModel/issues/7
Bonus: Clarify that mutually-ordered is irreflexive. Irreflexivity of some other relations follows naturally from this.
=> Vulkan-MemoryModel issue 7: Clarify that scoped modification order only relates atomic writes

xml/README.adoc
I think this is referring to `../registry.txt`, and that's covered in the root README.
=> Remove readme.txt reference

appendices/memorymodel.txt
See https://github.com/KhronosGroup/Vulkan-MemoryModel/pull/17 for the corresponding alloy change.
Scoped modification order only relates writes (not reads), so this special case for atomics was incomplete and  necessary.
=> Memory model: Remove (unnecessary) scoped modification order case from location-ordered definition

xml/vk.xml
`VK_KHR_win32_surface` is an extension, not a feature
=> Fix the VK_EXT_full_screen_exclusive dependency on VK_KHR_win32_surface

appendices/VK_INTEL_shader_integer_functions2.txt, appendices/spirvenv.txt, chapters/features.txt, xml/vk.xml
The related SPV extension has already been merged.
@jekstrand
=> Add VK_INTEL_shader_integer_functions2

xml/vk.xml
Pastel was the project name for SwiftShader's initial Vulkan
implementation, but won't live on as a product name.
Note that at this point SwiftShader's VK_KHR_driver_properties
implementation has not landed yet:
https://swiftshader-review.googlesource.com/c/SwiftShader/+/22690
So there's no risk of the old enum name being used already and this
renaming causing any issues.
Bug: https://issuetracker.google.com/issues/116336664
Bug: b/130019658
=> Rename Pastel driver ID to SwiftShader

chapters/renderpass.txt
Fix copy-paste error referencing wrong subpass in `VkRenderPassCreateInfo` VU.
=> Fix wrong subpass in VkRenderPassCreateInfo VU

scripts/generator.py
pathlib name is not compatible in python2 and python3, it's named pathlib2 in python2.
Fixes #1011
=> Compatible pathlib for py2 and py3 in script/generator.py

chapters/renderpass.txt
These VUs seem redundant to [VUID-VkRenderPassCreateInfo-pDependencies-00837](https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html#VUID-VkRenderPassCreateInfo-pDependencies-00837) and its siblings.
There was perhaps some attempt at being more generic. But any pipeline bind point is unlikely to support `VK_PIPELINE_STAGE_HOST_BIT` anyway. And not sure why any future self-dependencies could not theoretically be non-graphic.
=> Remove redundant render pass VUs

chapters/memory.txt
Made clear that the note is not normative and only points out an instance of a data race that is not satisfied implicitly as some may expect.
Closes #889
=> Clarify the memory mapping note about invalidation

chapters/synchronization.txt
Removed misleading note about multiple execution dependencies.
Fixes #812
=> Removed misleading note as per 812

chapters/synchronization.txt
This change makes clear that VK_ACCESS_MEMORY_READ_BIT and VK_ACCESS_MEMORY_WRITE_BIT are meant to be equivalent to setting all applicable READ/WRITE access flags.
Closes #1007
=> Clarify the ACCESS_MEMORY bit flags

scripts/validitygenerator.py, xml/vk.xml
Effectively adds:
> `flags` **must** be `0`
to `VkRenderPassCreateInfo`, `VkRenderPassCreateInfo2KHR`, and `VkShaderModuleCreateInfo` (which are disabled, but defined in upcoming extensions).
And to others based on the extensions and vulkan version chosen to build,
=> Ignore disabled Bits in validity

chapters/VK_KHR_surface/wsi.txt
- split in sections
- move orphaned paragraphs
- concentrate behavior descriptions to
vkGetPhysicalDeviceSurfaceFormatsKHR (non-2)
- remove two paragraphs restating the obvious
- remove old hack
=> Restructure WSI Query chapter 

scripts/conventions.py
to be consistent with the preference for `elink:` and `tlink:`
Example diff:
=> Prefer slink in autovalidity

chapters/clears.txt
The original VUs said "must: each only include X". That makes the two VUs contradictory for depth+stencil format.
New VUs should allow `DEPTH` (for depth, or depth+stencil format). `STENCIL` (for stencil,  or depth+stencil format), or `DEPTH | STENCIL` (for depth+stencil format).
=> Fix vkCmdClearDepthStencilImage::aspectMask VU

chapters/cmdbuffers.txt
The following VU added by VK_KHR_timeline_semaphore is accurate, and covers the same invalid cases as this does, but factoring in timeline semaphores.
=> Hide outdated VU in face of timeline semaphores

chapters/features.txt, chapters/formats.txt, config/attribs.txt
Fix suggestion for #395.
- Add the formats to Required Format tables, with precondition on the feature
- Update feature description with explicitly listed format
- Update description with note about enabling being optional
- Update description with note about discrepancy vs SPIR-V formats
=> Clarify shaderStorageImageExtendedFormats feature

chapters/VK_KHR_swapchain/wsi.txt
Most of the drivers seem to report `minImageCount==2`, which would make the swapchain uncreatable due to the another VU requiring the count to be 1 for shared present modes.
=> Fix minImageCount VU wrt the shared present modes

chapters/cmdbuffers.txt
Having primary command buffer with both `VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT` and `VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT` does not make sense. Cannot submit multiple times to make use of simultaneous flag.
For secondaries `SIMULTANEOUS` controls whether they can be recorded multiple times, so the situation is different.
=> Prevent primary with both ONE_TIME and SIMULTANEOUS_USE

chapters/cmdbuffers.txt
- remove VUID requiring primary of a secondary to be pending. I think by definition secondary is pending if primary is, and there is already secondary specific VUID.
- remove VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT language covered by VUIDs
=> Remove redundant command buffer SIMULTANEOUS_USE language

chapters/cmdbuffers.txt
already covered by implicit VUID-vkCmdExecuteCommands-bufferlevel
=> Remove redundant vkCmdExecuteCommands VU

chapters/memory.txt
restriction already in [`VUID-vkMapMemory-memory-00678`](https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html#VUID-vkMapMemory-memory-00678)
closes #1142
=> Make note redundant vkMapMemory restriction

chapters/cmdbuffers.txt
- do not use "reverts back" with invalid state
- clear out ambiguities in primary-secondary lifecycle linkage
- include the case when completion moves to the invalid state
- clarify that moving secondary between the pending and
execution state does not invalidate any other primary it
may be recorded in
=> Clarify command buffer state

Makefile, config/chunkindex/chunked.css, config/chunkindex/chunked.js, config/khronos.css, scripts/genanchorlinks.py
- add anchor handles to chapters
- chunked already had them sneaked in with the build script, so replace with the asciidoctor feature. Difference is it is on the left of the chapter header instead. Also the symbol is different (but that can be changed in the CSS).
- add similar anchor handles to each VU
It is pretty standard on modern websites (such as here on GitHub when viewing md file). Helps people to link to stuff without having to fish inside the html source for the anchor ids. Additionally makes the VUID of VU more visible (hovering over link usually shows the URL, as well as clicking it should apply it to the address bar).
preview: http://vulkan.hys.cz/orig/pr1157/vkspec.html
hover mouse over a chapter header, or over a VU statement to see a clickable link symbol.
=> Add anchor handles to chapters and VUIDs

chapters/cmdbuffers.txt
follow-up from #1153
Remove note that only reiterates for the third time what `VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT` does.
On the bit introduction there already is:
> `VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BI`T specifies that a command buffer **can** be resubmitted to a queue while it is in the _pending_ state, and recorded into multiple primary command buffers.
As well as it is covered by VUs.
=> Remove redundant SIMULTANEOUS_USE note

xml/vk.xml
Codeplay Software Ltd is a ISV, and as such doesn't have a PCIe ID to use for the `VkPhysicalDeviceProperties::vendorID` in our [ComputeAorta](https://codeplay.com/products/computesuite/computeaorta) product.
Reserve the next free ID from `VkVendorId` in vk.xml
=> Reserve Codeplay vendor ID

chapters/debugging.txt, xml/vk.xml
- Fix returned array implicit VUs
- Rewrite text to be more consistent (based on `vkGetPhysicalDeviceQueueFamilyProperties`)
- Explicitly state variability (aka "lifetime") of retrieved results. (I assume active tools list can change; e.g. tools being switched on and off outside the Vulkan scope.)
=> Fix vkGetPhysicalDeviceToolPropertiesEXT

appendices/glossary.txt, appendices/memorymodel.txt, chapters/cmdbuffers.txt, chapters/synchronization.txt
- add happens-before to glossary for better search
- convert "happens before" to happens-before
- fix one case of "happens before" where it probably means
"logically earlier stage"
=> Fix "happens before" per glossary and style

appendices/VK_EXT_image_drm_format_modifier.txt, chapters/VK_EXT_debug_utils.txt, chapters/VK_KHR_surface/wsi.txt, chapters/VK_KHR_swapchain/wsi.txt, chapters/VK_NV_external_memory_capabilities/external_image_format.txt, chapters/cmdbuffers.txt, chapters/descriptorsets.txt, chapters/memory.txt, chapters/pipelines.txt, chapters/renderpass.txt, chapters/resources.txt, chapters/synchronization.txt, config/spec-macros/extension.rb, style/extensions.txt, style/markup.txt, styleguide.txt
- resolves new asciidoctor warnings
- obviates the need to escape ->
=> Update markup extension

xml/vk.xml
When looking at the registry, I see that `VkDisplayKHR` has no parent. This handle is acquired by functions with a `VkPhysicalDevice` dispatchable object. Shouldn't the parent then be `VkPhysicalDevice`?
If that's the case, then by extension it makes sense to remove `VkPhysicalDevice` from the  `VkDisplayModeKHR` parent so that it only has `VkDisplayKHR`.
=> Tweak parents of VkDisplayKHR and VkDisplayModeKHR.

chapters/synchronization.txt
This will make it consistent with the paragraph preceding it.
=> Minor text edit for consistency

include/vulkan/vulkan.h, scripts/genvk.py, xml/Makefile, xml/vk.xml
DirectFB interfaces was largely widespread in the GNU/Linux embedded world and the VK_EXT_directfb_surface extension allows rendering via DirectFB on such platform.
A screenshot with simple Vulkan examples running with the VK_EXT_directfb_surface extension is available on the HiGFXback project:
https://github.com/caramelli/higfxback/wiki/DirectFB#vulkan-rendering
And the yagears project provides sample code to use this VK_EXT_directfb_surface extension:
https://github.com/caramelli/yagears
Nicolas Caramelli
=> Add VK_EXT_directfb_surface

appendices/VK_EXT_directfb_surface.txt, appendices/boilerplate.txt, chapters/VK_EXT_directfb_surface/platformCreateSurface_directfb.txt, chapters/VK_EXT_directfb_surface/platformQuerySupport_directfb.txt, chapters/VK_KHR_surface/wsi.txt, include/vulkan/vulkan.h, scripts/genvk.py, xml/Makefile, xml/vk.xml
I don't know what to define in the .Valid usage section for the number associated with the VUID, so this section is missing.
Nicolas Caramelli
=> Add specification for VK_EXT_directfb_surface extension

config/chunkindex/README.adoc, config/chunkindex/lunr.js, package-lock.json, package.json
allows to simply `npm install` all deps
=> Add lunr to package.json

config/loadable_html/extension.rb
Add noscript fallback for html, so that the optional script added in #702 is simply skipped.
demo: http://vulkan.hys.cz/noscript/vkspec.html (works with either JavaScript on or off)
=> Add noscript fallback for html

chapters/cmdbuffers.txt
ex #1284: probably a typo.
All elements of unprotected command buffer are required to be unprotected, I think.
=> Fix typo in protected submit VU

chapters/textures.txt
The ```y``` coordinate is outside the ```v``` function's parantesis the the top formula regarding anisotropic filtering.
=> Fix paranthesis mistake in chapters/textures.txt

xml/vk.xml
While generating language bindings from vk.xml I noticed that the pNext member in structs is not marked as optional, but from what i understand pNext should be allowed to be null.
Example from khronos.org: "pNext is NULL or a pointer to the next structure in a structure chain."
(https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkBaseInStructure.html)
Maybe I'm misinterpreting what optional means in this context.
=> pNext pointers not marked as optional in vk.xml

chapters/descriptorsets.txt
VkPushConstantRange takes ShaderStageFlags not PipelineStageFlags.
=> Fix example code for VkPushConstantRange

chapters/formats.txt
Small formatting typo I stumbled upon.
=> Remove extraneous newline from texel block size table

xml/vk.xml
Followup to #1379. There is now a semantically meaningful schema
attribute mapping handles to corresponding VK_OBJECT_TYPES enum names.
This removes the comments which were previously being used by some
downstream consumers of the XML to infer this information on the basis
that (a) they are not defined to be usable for this purpose (b) they are
incomplete and (c) we have no intention of maintaining them in the
future when new handle types are defined.
=> Remove redundant / incomplete handle comments from VkObjectType enums

chapters/interfaces.txt
The `Sampled=1` bit should go in front of `OpTypeImage` instead of `OpTypeSampler` in the comment about variables sharing the same descriptor set and binding. `OpTypeSampler` doesn't have a `Sampled` operand.
=> `Sampled=1` should apply to `OpTypeImage`

chapters/interfaces.txt
I attempted to make the `PatchVertices` documentation clearer. See #1461 for the discussion that motivated this change.
=> Clarify PatchVertices documentation for tessellation shaders.

xml/vk.xml
These are additional types that are defined in `vk_video` but have not been referenced in `vk.xml`.
This should ideally be kept up to date. I am using this information for the generation of bindings.
=> Add additional `vk_video` types

xml/vk.xml
I think this `optional` attribute is missing here in `vkGetPhysicalDeviceVideoFormatPropertiesKHR`.
=> Add missing optional

appendices/VK_EXT_acquire_drm_display.txt, chapters/VK_EXT_acquire_drm_display/acquire_drm_display.txt, chapters/VK_EXT_direct_mode_display/acquire_release_displays.txt, include/vulkan/vulkan.h, xml/vk.xml
This pull request is a continuation of the work done in https://github.com/KhronosGroup/Vulkan-Docs/pull/1525, where it was discussed that instead of having a Wayland-centered approach to DRM leasing to handle VR headset (see  #1001 and #1450), we would change the design to have a more generic FD-based approach.
[Mesa implementation](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/11014)
[Monado usage](https://gitlab.freedesktop.org/monado/monado/-/merge_requests/832)
=> Add VK_EXT_acquire_drm_display

xml/vk.xml
It is generally expected that "top level" includes are relative to the `./include` directory in this repo.  The video headers, sitting at the root of the `./include` folder in `./include/vk_video/vulkan_video_*.h`, are listed as `vk_video/vulkan_video_*.h` in `vk.xml`.  Likewise the `vk_platform` type-header is supposed to be listed as `vulkan/vk_platform.h` to match its relative location under `./include`.
=> vk.xml: Include `vk_platform` type-header from `vulkan/vk_platform.h`

scripts/reflow.py
Reflow script run from github CI assumed vuidCounts.py is present, which is only true in the internal repository. Don't require it if not needed.
=> Fix github CI

xml/vk.xml
This caused some issues with search paths per #1573. There will probably
be a downstream change to move the vk_video/ headers under
vulkan/vk_video instead of in a parallel directory. We are not entirely
settled on how to move this forward at the moment and there's a mix of
philosophical correctness and concrete build issues being discussed in #1573.
=> Revert vk_platform path change from PR #1538

xml/vk.xml
A work in progress version can be found here: https://github.com/DadSchoorse/Vulkan-Docs/tree/VK_EXT_disable_cube_map_wrap
=> Reserve extension number for VK_EXT_disable_cube_map_wrap.

scripts/extensionmetadocgenerator.py
Remove Issue title which will cause GitHub Issue opening button to be disabled
Plus make the contact links open in new window for convenience.
=> Mitigate misuse of contact links

xml/vk.xml
Utilizing the python scripts for code generation that was dependent on the len attribute, I found the pData member did not have a len attribute and seemed to be related to the dataSize member though I did not see any official documentation on the matter.
=> vk.xml: Adding len attribute to VkCuModuleCreateInfoNVX struct member pData.

xml/vk.xml
This is a follow-up to #1515, adding all the newly introduced types that are defined in `vk_video` but have not been referenced in vk.xml. I am using this information for the generation of bindings.
=> Register remaining newly introduced `vk_video` types in vk.xml

chapters/memory.txt
Remove VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT from VkExportMemoryWin32HandleInfoKHR.
Closes #1551
=> Remove exporting of D3D memory handles

chapters/resources.txt
=> Fix typo for VK_REMAINING_MIP_LEVELS.

chapters/renderpass.txt
Separate depth or stencil readonly image layouts only exist in
Vulkan 1.1+ or via extension. It should not apprear at VUID 03280
and 03282 in 1.0.
The impacted image layouts are:
- VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL
- VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL
=> Minor changes about separate depth or stencil readonly image layout

appendices/VK_AMD_gcn_shader.txt, appendices/VK_AMD_gpu_shader_half_float.txt, appendices/VK_AMD_gpu_shader_int16.txt, appendices/VK_AMD_shader_ballot.txt, appendices/VK_AMD_shader_explicit_vertex_parameter.txt, appendices/VK_AMD_shader_fragment_mask.txt, appendices/VK_AMD_shader_trinary_minmax.txt, appendices/VK_AMD_texture_gather_bias_lod.txt, appendices/VK_EXT_buffer_device_address.txt, appendices/VK_EXT_descriptor_indexing.txt, appendices/VK_EXT_fragment_density_map.txt, appendices/VK_EXT_shader_demote_to_helper_invocation.txt, appendices/VK_EXT_shader_image_atomic_int64.txt, appendices/VK_HUAWEI_subpass_shading.txt, appendices/VK_INTEL_shader_integer_functions2.txt, appendices/VK_KHR_fragment_shading_rate.txt, appendices/VK_KHR_shader_subgroup_uniform_control_flow.txt, appendices/VK_KHR_workgroup_memory_explicit_layout.txt, appendices/VK_NV_shader_sm_builtins.txt
There is still some inconsistency with GLSL, some extensions use `GL_...`  and others `GLSL_...`. E.g. `VK_EXT_shader_atomic_float` uses `GL_EXT_shader_atomic_float` but `VK_EXT_shader_atomic_float2` `GLSL_EXT_shader_atomic_float2`. But I'm not sure which option is preferred there.
=> Clean up links to GLSL and SPIR-V extensions

appendices/VK_KHR_multiview.txt, appendices/VK_KHR_ray_query.txt, appendices/VK_KHR_ray_tracing_pipeline.txt, appendices/VK_KHR_shader_atomic_int64.txt
These were missed in the last spec update.
=> Replace manual github links for SPIR-V and GLSL extensions

chapters/clears.txt, chapters/descriptorsets.txt, chapters/primsrast.txt, chapters/resources.txt
This
- fixes AsciiDoc "If" usage in two places to fix spaces, one with comma, in the rendered PDF
- adds two commas in total
- adds missing spaces in a comma-separated list
Sorry for not using the commit titles properly - For 3 of 4, it's detailed in the descriptions instead.
=> A handful of AsciiDoc "If" and punctuation fixes

chapters/features.txt
This fixes two minor typos in the Feature Requirements section, noticed with #1747.
=> Fix two typos in Feature Requirements section

chapters/textures.txt
This removes a syntax-breaking comma and wrong extra parentheses in the formula for "Texel Anisotropic Filtering" through minimal changes, and I've checked the rendering of the fix using LyX.
I think the original error came from copy-pasting formula parts from u for v.
=> Fixed formula for "Texel Anisotropic Filtering"

xml/vk.xml
Thus far `structextends` has always noted the name of the struct it extends directly, not one of the aliases redirecting to it.  Our generator gets "confused" by this because we haven't taught it to perform an alias lookup here, and it seems cleaner to solve it in vk.xml directly.  After all, many more structs that were stabilized in 1.3 had `structextends` references to it changed to drop the (`KHR`) extension suffix.
=> xml/vk: Reference underlying type instead of typedef in `structextends`

xml/vk.xml
NZXT is working on software for gamers which will require us to build a vulkan layer. Additional details on this software cannot be made public at this time.
=> add author id for NZXT Inc.

chapters/VK_KHR_swapchain/wsi.txt
Reading the swapchain specs, I was surprised to stumble across [the following](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkCreateSwapchainKHR.html#:~:text=The%20VkSwapchainKHR%20is%20a%20child%20of%20the%20device%2C%20and%20must%20not%20be%20destroyed%20before%20the%20device.):
> The `VkSwapchainKHR` is a child of the `device`, and **must** not be destroyed before the `device`.
My understanding is that children of a device must be destroyed before the device itself, so I'm tempted to assume this sentence is mistaken. If it's not, perhaps some additional explanation might be helpful.
=> Fix order of swapchain vs device destruction.

chapters/fundamentals.txt
Simplify typo alias example to non-extension elements 
avoids 1.0 build warning
=> Simplify example to non-extension elements

chapters/VK_EXT_pipeline_properties/pipeline_properties.txt, chapters/VK_KHR_surface/wsi.txt, chapters/VK_KHR_swapchain/wsi.txt, chapters/features.txt
- Add VU for `pipelinePropertiesIdentifier` feature
- change VU from when `VK_EXT_image_compression_control_swapchain` is enable to `imageCompressionControlSwapchain` feature bit is enabled (unless there is some hidden reason why it shouldn't use the feature bit here)
=> minor fixes for 1.3.213 spec

chapters/copies.txt
As described in #1855 part about ```vkCmdResolveImage2``` is at the end of sub-chapter 20.6 ("Buffer Markers") while it should be after ```vkCmdResolveImage``` so at the end of sub-chapter 20.5 ("Resloving Multisample Images").
=> Make VkImageResolve2 appear right after VkImageResolve

xml/vk.xml
I'm not a native speaker but I think this should be "an" object. At least "of an object" has much more Google results compared to "of a object".
I've run `make validate install test` and `(cd .. && make generated)` as the README in the xml directory told me. Is there anything else that I need to run to regenerate more resources?
=> fix typo: Initialization of **an** object has failed

appendices/spirvenv.txt, chapters/resources.txt
No need for the `ifdef` wrapper for standalone SPIR-V VUs since its in the unified SPIR-V spec, there isn't one for `VUID-StandaloneSpirv-PerVertexKHR-06777` which also references `PerVertexKHR`
=> minor fixes for 1.3.215 spec

appendices/VK_EXT_non_seamless_cube_map.txt, chapters/features.txt, chapters/samplers.txt, chapters/textures.txt, proposals/VK_EXT_non_seamless_cube_map.asciidoc, xml/vk.xml
Core Vulkan always uses seamless cube map edge wrapping. Out of bounds accesses select texels from the neighboring face with linear filter, or get clamp to edge behavior with nearest filter. D3D9 has no seamless cube maps, the sampler wrap modes apply within the selected face. OpenGL has a global toggle with ARB_seamless_cube_map and a per texture toggle with ARB_seamless_cubemap_per_texture.
For DXVK (D3D9 to Vulkan translation) we need D3D9 cube map behavior since games were designed with it in mind and some don't look correct with seamless cube map edge handling. Zink or other OpenGL translation layers might also be interested in non-seamless cube maps to implement the previously mentioned OpenGL extensions.
anv implementation: …
=> Add VK_EXT_non_seamless_cube_map

.github/workflows/CI.yml
As requested by @oddhack 
---
~Intermediates are also published and communicated through artifacts. Unfortunately this is way slower than the original ±11m (not to mention much slower than GitLab CI, which sits at about ±7m) because the artifact is a whopping 190MB (compared to ±40MB on GitLab CI) despite including less files. This artifact takes about 4 minutes to download per job :(~
=> github/ci: Split `steps` into individual `jobs` like GitLab CI

chapters/renderpass.txt
There is a `VkRenderingAttachmentInfo::imageLayout` and is what the Validation Layers are using for these VUs, think this is a simple typo
=> VkRenderingAttachmentInfo VU using wrong field name

appendices/spirvenv.txt
This came up in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4148
The description of ` maintenance4` feature says
> The interface matching rules allow a larger output vector to match with a smaller input vector, with additional values being discarded.
and there is language in the [interface matching section](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#interfaces-iointerfaces-matching) but there is no explicit VUID to assign to this.
Open as always to suggestions on wording or placement of the VU
=> Add VK_KHR_maintenance4 relaxed interface VUID

chapters/fxvertex.txt
The current section is missing a definition for `offset` and does not mention what happens with `vertexOffset` from the indexed variants, but introduces a different quantity with the same name.
The updated text still doesn't talk about indirect draws, which might be worth adding.
This is the first time I do conditional markup, please let me know if I didn't get it right.
=> Rework Vertex Input Address Calculation

chapters/fragops.txt
`StencilRefLessFrontEXT` execution mode was used in part about early depth tests where it should be `DepthLess` execution mode.
=> Change StencilRefLessFrontEXT to DepthLess in early depth test part in Fragment Operations chapter

chapters/renderpass.txt
PR for issue #1828
According to the validation rule of VUID-VkRenderPassCreateInfo-srcSubpass-02517 and VUID-VkRenderPassCreateInfo-dstSubpass-02518:
VUID-VkRenderPassCreateInfo-srcSubpass-02517
The srcSubpass member of each element of pDependencies must be less than subpassCount
VUID-VkRenderPassCreateInfo-dstSubpass-02518
The dstSubpass member of each element of pDependencies must be less than subpassCount
the srcSubpass should always be less than subpassCount to make sure it points to a valid subpass, but VK_SUBPASS_EXTERNAL seems to be an exception. It is fine to create a dependency like this (in pseudo code):
vk::SubpassDependency {
src_subpass: vk::SUBPASS_EXTERNAL,
src_stage_mask: vk::PipelineStageFlags::COLOR_ATTACHMENT_OUTPUT,
dst_access_mask: …
=> Relax the rule of VUID-VkRenderPassCreateInfo-srcSubpass-02517 and VUID-VkRenderPassCreateInfo-dstSubpass-02518

xml/vk.xml
This is the driver ID for Dozen, the Vulkan-on-Direct3D driver in Mesa.
=> Add a new driver id VK_DRIVER_ID_MESA_DOZEN

chapters/shaders.txt, xml/vk.xml
VkShaderModuleCreateInfo appears both as an explicit parameter, and in
the pNext chain of VkPipelineShaderStageCreateInfo, The validity
generator doesn't understand this case fully.
Proposed solution is to add an explicit VU to vkCreateShaderModule
expressing the pNext constraint; make sure implicit VU for pNext are
suppressed; and properly tag the structextends attribute for the single
structure extending VkShaderModuleCreateInfo.
Fixes #1883
=> Fix XML tagging of VkShaderModuleCreateInfo and add explicit VU

.github/workflows/CI.yml, .gitlab-ci.yml
_This complements a similar change done to the GitLab CI script._
Rust's Vulkan bindings, provided by [the Ash crate], rely on rather strict rules/conventions in vk.xml or otherwise fail to generate.  In order to provide more insight into the effect of spec changes to this project, and hopefully catch mishaps earlier (ie. naming rules for enum variants with respect to the typename of the enum) regenerate and build-test the Rust crate in the CI.
Since Rust bindings are not part of the official Khronos Vulkan SDK / release this check is currently allowed to fail.  Over time this task can be expanded to notify Ash maintainers when PRs merged to `main` break our build, so that we can resolve it quickly or request spec changes before they are released hence set-in-stone.  Additionally release …
=> GitHub CI: Regenerate and build-test Rust Vulkan bindings (Ash crate)

appendices/spirvenv.txt
The `Hit Value` to my knowledge is not always going to be constants so I assume this VU is just misplaced and belongs in the runtime section
=> Move Hit Kind VU to runtime

appendices/spirvenv.txt
There is a VUID
> VUID-StandaloneSpirv-None-04638
Scope for memory must be limited to Device, QueueFamily, Workgroup, ShaderCallKHR, Subgroup, or Invocation
and for `Subgroup` memory Scope in Vulkan 1.0 there is no VUID "banning" them, but I assumed if someone is using the `VK_EXT_shader_subgroup_vote`/`VK_EXT_shader_subgroup_ballot` in a 1.0 application is would still be valid
(related `spirv-val` PR https://github.com/KhronosGroup/SPIRV-Tools/pull/4869)
=> Add Vulkan 1.0 for supgroup memory scope

.github/workflows/CI.yml, Makefile
PR just to test if Docker container cache has refreshed on Github Actions, yet.
Branch name courtesy of a long-ago letter in *The Economist*: http://www.ojohaven.com/fun/spelling.html
=> Add codespell tool to 'allchecks' target used by CI

chapters/drawing.txt
There is already 2 VUIDs for `drawIndirectFirstInstance` in the struct and no need for it in the function as well
> VUID-VkDrawIndirectCommand-firstInstance-00501
If the drawIndirectFirstInstance feature is not enabled, firstInstance must be 0
> VUID-VkDrawIndexedIndirectCommand-firstInstance-00554
If the drawIndirectFirstInstance feature is not enabled, firstInstance must be 0
Removing the function in favor of the structure VUID seem more consistent with rest of VUs
=> Remove redundant drawIndirectFirstInstance VUID

appendices/boilerplate.txt
The macro was added to the Vulkan headers starting with VK_HEADER_VERSION 174.
Closes #1917
=> Add a NOTE to VK_USE_64_BIT_PTR_DEFINES to define its availability

appendices/spirvenv.txt, chapters/commonvalidity/draw_dispatch_common.txt
Currently trying to implement both VUID `04115` and `04469` in the Validation Layers, but when I have the following shader
```swift
%type_image = OpTypeImage %uint 2D 0 0 0 2 Rgba8ui
%texelU3 = OpConstantComposite %v3uint %uint_1 %uint_1 %uint_1
OpImageWrite %image %int_1 %texelU3 ZeroExtend
```
`Rgba8ui` should become `VK_FORMAT_R8G8B8A8_UINT` and only writing 3 components triggers 
> VUID-vkCmdDraw-None-04115
If a VkImageView is accessed using OpImageWrite as a result of this command, then the Type of the Texel operand of that instruction must have at least as many components as the image view’s format
but I would purpose it might be more beneficial to have this checked at `vkCreateShaderModule` time instead of waiting until draw time (unless someone can point to CTS tests verifying all …
=> Add standalone VU for OpImageWrite component mismatch

appendices/spirvenv.txt
Currently, there is code in `spirv-val` to check the `Storage Classes` in `SPV_KHR_ray_tracing` and while I am adding support right now, I realized there is duplicate language in the Vulkan spec that is already well documented in the [SPV_KHR_ray_tracing](https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_ray_tracing.html#_modifications_to_the_spir_v_specification) spec
My argument for the removal is
- The Vulkan Spec was missing `ShaderRecordBufferKHR` so it is not complete in the Vulkan spec currently
- There are much more details missing from the SPIR-V spec missing here (eg. a VU for `HitAttributeKHR` can only be read from `AnyHitKHR` and `ClosestHitKHR`)
- single origin to change in future if another Storage Class …
=> Add missing SPV_KHR_ray_tracing storage class VUID

appendices/spirvenv.adoc
`VUID-StandaloneSpirv-None-04686` is already implemented in SPIR-V Tools and I can add the `TaskPayloadWorkgroupEXT` addition if wanted
-----
- `VUID-StandaloneSpirv-PrimitivePointIndicesEXT-07103`
- `VUID-StandaloneSpirv-PrimitiveLineIndicesEXT-07104`
- `VUID-StandaloneSpirv-PrimitiveTriangleIndicesEXT-07105`
are already found in the Built-in section for example
> VUID-PrimitivePointIndicesEXT-PrimitivePointIndicesEXT-07042
The PrimitivePointIndicesEXT decoration must be used only with the the OutputPoints Execution Mode
=> remove ifdef from standalone spirv VUID

appendices/spirvenv.adoc
Adds missing runtime shader VUID for
- `maxTaskWorkGroupInvocations`
- `maxTaskWorkGroupSize`
- `maxMeshWorkGroupTotalCount`
- `maxMeshWorkGroupCount`
- `maxMeshWorkGroupInvocations`
- `maxMeshWorkGroupSize`
I am not sure 100% if 
> VUID-vkCmdDrawMeshTasksEXT-groupCountX-07083
groupCountX must be less than or equal to VkPhysicalDeviceMeshShaderPropertiesEXT::maxTaskWorkGroupCount[0]
Would actually use `maxMeshWorkGroupCount` if there is no Task shader in the pipeline. If this the case, can adjust the VU in `vkCmdDrawMeshTasks*` to handle both sets
-----
Note I was going to add 
- `maxTaskPayloadSize`
- `maxTaskSharedMemorySize`
- `maxTaskPayloadAndSharedMemorySize`
- `maxMeshSharedMemorySize`
- `maxMeshPayloadAndSharedMemorySize`
- `maxMeshOutputMemorySize`
- …
=> Add missing VK_EXT_mesh_shader limit VUID

include/vulkan/vulkan.h
With https://github.com/KhronosGroup/Vulkan-Tools/pull/670 resolved, wayland-client.h can be removed from Headers. This has been cooking in openSUSE for a while, and other vulkan infrastructure (vulkan-{tools,validationlayers}, glslang, spirv-tools, shaderc) still build fine.
=> Drop wayland-client.h include

chapters/VK_NV_mesh_shader/drawing.adoc, chapters/commonvalidity/draw_mesh_limits_common.adoc
from https://github.com/KhronosGroup/Vulkan-Docs/pull/1931#issuecomment-1241088493 (cc @pdaniell-nv for taking a look)
created a `draw_mesh_limits_common.adoc` to match what we do for `trace_rays_limits_common.adoc`
=> Add maxMeshWorkGroup*Count limits when no task shader is used

appendices/spirvenv.adoc, chapters/pipelines.adoc
The VUs removed are already in the SPIR-V section, for example `VUID-VkPipelineShaderStageCreateInfo-stage-07061` is the same as 
> VUID-RuntimeSpirv-MeshEXT-07115
For mesh shaders using the MeshEXT Execution Model the OutputVertices OpExecutionMode must be less than or equal to VkPhysicalDeviceMeshShaderPropertiesEXT::maxMeshOutputVertices.
------
The 2 sets of VUs added make the following 2 shaders illegal
```swift
OpExecutionMode %mainMesh OutputVertices 1
OpExecutionMode %mainMesh OutputPrimitivesEXT 1
OpSetMeshOutputsEXT 2 2 
```
```swift
OpExecutionMode %mainMesh OutputVertices 0
OpExecutionMode %mainMesh OutputPrimitivesEXT 0
; Can't find spec language saying OpSetMeshOutputsEXT MUST be called if no other Output is also not written
```
=> Add SPIR-V VU for mesh shader output count

chapters/interfaces.adoc
About to add validation support and thought it meant "if another `OpExecutionMode` is used it is invalid" which doesn't make sense so updated it to be what I think it was intended to mean from the SPIR-V spec saying
> Each OpEntryPoint with the MeshEXT Execution Model must have an OpExecutionMode with exactly one of OutputPoints, OutputLinesEXT, or OutputTrianglesEXT Execution Modes.
=> Clarify VK_EXT_mesh_shader builtin execution modes

scripts/genvk.py
@lygstate This should move the WinRT extension into vulkan_win32.h
@oddhack @jjulianoatnv Could you signoff if you are happy with this change?
=> Move WinRT extensions into vulkan_win32.h header

chapters/fragops.adoc
coverageToColorLocation is in VkPipelineCoverageToColorStateCreateInfoNV, not VkPipelineSampleLocationsStateCreateInfoEXT.
=> Fix a typo in vkCmdSetCoverageToColorLocationNV

chapters/formats.adoc
`VK_FORMAT_R32_SFLOAT` should support `VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT` without `VK_EXT_shader_atomic_float`
=> Fix `VK_FORMAT_R32_SFLOAT` note

appendices/VK_KHR_create_renderpass2.adoc
aspectMask is not specified in VKAttachmentDescription2KHR but in VkAttachmentReference2KHR
=> Fix incorrect link in VK_KHR_create_renderpass2

Makefile, vkspec.adoc
{chapters}/ is used everywhere else.  This makes it possible to override the macro consistently across the spec.
=> Use {chapters}/ in vkspec.adoc instead of chapters/

chapters/VK_EXT_debug_utils.adoc
The DebugUtils commands that allow a developer to associate data with a given object handle were unclear in a number of places. In particular, if the object passed in was an instance-level or physical-device-level object, what were the restrictions. This language attempts to rectify that.
Associated Issues: #1668
NOTE: This replaces PR #1901 which was submitted to resolve this issue but appears to have gone stale.  But @pixelcluster deserves kudos for attempting to get this fixed since it lead to many good discussions with @krOoze as well.
=> Clarify DebugUtils object support

BUILD.adoc, chapters/introduction.adoc, registry.adoc, style/extensions.adoc, style/introduction.adoc, style/revisions.adoc, style/writing.adoc
There were some out of date normative reference citations, and incorrect cross-references between the specification, style guide, and registry schema documents.
* Updates normative reference sections and cites them appropriately within each document.
* Updates description of <enum> XML tags in the schema document to refer to the style guide for computing numeric enumerant values.
* Updates corresponding description in the style guide to reference the schema document.
* Miscellaneous minor markup fixes.
Fixes #2069
=> Update citations and cross-references

appendices/VK_EXT_shader_object.adoc
[VK_EXT_shader_object] @daniel-story
Hi, I see the function `vkCmdCreateShadersEXT` is used in the shader object sample code, but maybe `Cmd` is not needed.
=> Fix typo in sample code

chapters/video_decode_h265_extensions.adoc
Probably this was meant to reference StdVideoDecodeH265ReferenceInfo instead of StdVideoDecodeH264ReferenceInfo in "H.265 Decode Operations".
=> fix: reference StdVideoDecodeH265ReferenceInfo instead of H264 in H.265

xml/vk.xml
R component bits (10) is inconsistent with format name B10G11R11
=> fix VK_FORMAT_B10G11R11_UFLOAT_PACK32

xml/vk.xml
The order of component is inconsistent with format name.
=> fix VK_FORMAT_B5G5R5A1_UNORM_PACK16

xml/vk.xml
fix typos of formats in `vk.xml`.
`VK_FORMAT_R64G64_UINT`
`VK_FORMAT_R64G64_SINT`
`VK_FORMAT_R64G64_SFLOAT`
`VK_FORMAT_BC4_SNORM_BLOCK`
`VK_FORMAT_BC5_SNORM_BLOCK`
=> fix VK_FORMAT_R64G64 and VK_FORMAT_BC snorm formats

chapters/commonvalidity/draw_dispatch_common.adoc
This brings it in line with other similar statements in the immediate vicinity.
=> Fix a typo in VUID 08600

proposals/VK_EXT_mutable_descriptor_type.adoc
This PR fixes a very minor display issue in the VK_EXT_mutable_descriptor_type proposal. The `[[vk::]]` was displayed as a blank inline code block due to a missing escape char.
=> Fix missing display of vk:: in asciidoc in VK_EXT_mutable_descriptor_type proposal

chapters/shaders.adoc
=> Add explanation for subgroup vs dynamically uniform.

chapters/VK_EXT_swapchain_maintenance1/SwapchainPresentFenceInfo.adoc
The spec for `VkSwapchainPresentFenceInfoEXT` currently says:
> The application **can** destroy the wait semaphores associated with a given presentation operation when the associated fence is signaled, and **can** destroy the swapchain when the fences associated with all past presentation requests have signaled.
You can specify more than one swapchain, and each swapchain has its own fence, so there is not one single "associated fence". The present operation does not start until the wait semaphores have all been signalled, therefore the signalling of any fence must happen after the wait operation of all the semaphores. This PR clarifies that point.
=> Clarify mapping between wait semaphores and fences for swapchain present

proposals/VK_KHR_maintenance5.adoc
This PR fixes minor formatting issues in the `VK_KHR_maintenance5` proposal. E.g. an unintentional whitespace that turned a whole sentence into a code block and some wrong backticks.
=> Fix formatting issues in VK_KHR_maintenance5 proposal

chapters/resources.adoc
=> fix bad explanation of `VkBufferUsageFlags2CreateInfoKHR::usage`

appendices/spirvenv.adoc
Both VUID-RuntimeSpirv-TaskEXT-07294 and VUID-RuntimeSpirv-MeshEXT-07298 specify that the requirement only applies to task and mesh shaders, respectively, but VUID-RuntimeSpirv-x-06432 does not specify that it applies only to compute shaders. Since `maxComputeWorkGroupInvocations` is defined elsewhere as
> the maximum total number of **compute** shader invocations in a single local workgroup
this seems like an omission. This PR adds it, using the first two VUIDs as a template.
I've also given the same treatment to VUID-RuntimeSpirv-x-06429, VUID-RuntimeSpirv-x-06430 and VUID-RuntimeSpirv-x-06431, regarding the `maxComputeWorkGroupSize` limit.
=> Specify that VUID-RuntimeSpirv-x-06432 applies only to compute shaders

appendices/spirvenv.adoc
Fix parameter name "unnormalizedCordinates". Correct inappropriate markup.
=> Fix parameter typo "cordinates"

chapters/resources.adoc
The spec only mentions that `vkGetAccelerationStructureBuildSizesKHR` ignores `VkDeviceOrHostAddressKHR` values, but there are also `VkDeviceOrHostAddressConstKHR` values. `VkAccelerationStructureGeometryTrianglesDataKHR::transformData`, which is mentioned explicitly in the second half of the sentence as an exception, is a `VkDeviceOrHostAddressConstKHR` value. So I assume that both types are really meant to be ignored by this function. This PR clarifies that.
=> Explicitly state that VkDeviceOrHostAddressConstKHR is also ignored

appendices/VK_MSFT_layered_driver.adoc, chapters/devsandqueues.adoc, proposals/VK_MSFT_layered_driver.adoc, xml/vk.xml
This is my first attempt at a Vulkan extension. I chose `MSFT` for the vendor bits, but perhaps `EXT` would be more appropriate if MoltenVK has interest? Not sure if I'm supposed to also go ahead and update XML as part of this proposal or if that would come later.
This is needed to address https://github.com/KhronosGroup/Vulkan-Loader/issues/981. Without this, or something like it, VulkanOn12's physical devices can't be enumerated by LUID, or else they run the risk of being enumerated before a native driver for the same GPU.
=> Add VK_MSFT_layered_driver

.github/ISSUE_TEMPLATE/roadmap-feedback.md
Marty requested I setup a roadmap tempalte for Vulkan-Docs as adding directly to .github/ISSUE_TEMPLATES was not working correctly.
=> Update issue templates

scripts/antora-prep.py
Fixes https://github.com/KhronosGroup/Vulkan-Site/issues/29
=> Prevent xref text from having words crammed together across newlines

chapters/synchronization.adoc
Remove `VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_COPY_BIT_KHR` description from `VkPipelineStageFlagBits` (non-2) context.
Not sure if there should be non-2 alternative flag bit here or not. And `FlagBits2` description of this bit seem to differ. So further intervention of the Group might be warranted.
Nevertheless this bit description does not belong here, so I just simply delete it as part of this PR. (Which might not be the correct wholistic resolution as stated above. So consider this sort of a mergeable Issue ticket.)
=> Remove `VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_COPY_BIT_KHR` description from `VkPipelineStageFlagBits` context

appendices/spirvenv.adoc
There was a "not" missing here, otherwise 04917 makes the condition under which 04919 applies impossible.
=> Add missing "not" to 04917

xml/vk.xml
vkLatencySleepNV requires the use of a timeline semaphore, therefore this extension naturally depends on the timeline semaphore extension or Vulkan 1.2 where it is promoted to Core.
=> Add VK_KHR_timeline_semaphore dependency for VK_NV_low_latency2.

xml/vk.xml
This struct is only used to provide information, so it should be readonly.
=> make VkRenderPassStripeBeginInfoARM::pStripeInfos const

proposals/VK_EXT_image_compression_control.adoc
According to the [Spec](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkImageCompressionPropertiesEXT.html), `VkImageCompressionPropertiesEXT` will be empty unless a `VkImageCompressionControlEXT` is added to the `VkPhysicalDeviceImageFormatInfo2` `pNext` chain. This might be easy to miss if following the example as it was laid out before. 
Additionally, removed the signature of `vkGetPhysicalDeviceImageFormatProperties2` as it was not necessary.
=> Update VK_EXT_image_compression_control support query example

Makefile
Hey all,
I really wanted the spec for my kindle scribe so I poked a bit at getting asciidoc to generate epub. Not really sure if this is something you are all interested in but I figured the PR wouldn't hurt.
Here is a sample of the output generated by `./makeSpec -spec all epub`
[vkspec.zip](https://github.com/KhronosGroup/Vulkan-Docs/files/13789917/vkspec.zip)
Let me know if there is anything I can do to improve this. I mostly followed what was already there but I'm not an expert on asciidoc so I left out the bits I didn't know much about. This requires that https://docs.asciidoctor.org/epub3-converter/latest/ be installed but I didn't add any checks for that or anything as that seems to also be the case for pdf.
=> Add epub generation

scripts/reflib.py
In the page for [`PFN_vkVoidFunction`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/PFN_vkVoidFunction.html), the single description sentence is split over the Parameters and Description sections, like this:
> ## Parameters
> This type is returned from command function pointer queries, and **must** be
> ## Description
> cast to an actual command function pointer before use.
I found that `scripts/reflib.py` assumes every function pointer and function prototype page has parameter documentation, so I made it check that. I tested my changes by diffing the output of `./makeSpec -spec all manhtmlpages`, and found 13 affected files. First, these 3 changes seem correct to me:
* [`PFN_vkVoidFunction`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/PFN_vkVoidF …
=> Fix invalid generation of the "Parameters" section

appendices/VK_EXT_map_memory_placed.adoc, chapters/features.adoc, chapters/limits.adoc, chapters/memory.adoc, proposals/VK_EXT_map_memory_placed.adoc, xml/vk.xml
This extension adds support for requesting that a `VkDeviceMemory` object be mapped at a particular location in the client's address space.  This is similar to the `addr` parameter to the `mmap()` ioctl.  In order for this to succeed, the client **may** have to first reserve the address range via a platform-specific mechanism.
Fixes: https://github.com/KhronosGroup/Vulkan-Docs/issues/1832
- [Intel Linux implementation](https://gitlab.freedesktop.org/jekstrand/mesa/-/commits/anv/VK_EXT_map_memory_placed)
- [Crucible test](https://gitlab.freedesktop.org/jekstrand/crucible/-/commits/VK_EXT_memory_map_placed)
=> Add a new extension: VK_EXT_map_memory_placed

scripts/validitygenerator.py
addresses #2317 
Before:
After (spec):
After (refpages):
Affected functions:
=> Always generate failure code section even for functions without any errors specified

.github/workflows/CI.yml
The most problematic case is paired download/upload-artifact, which requires unique artifact names. Since we don't run this under a test matrix I don't think it should be a problem.
=> Resolve warnings in Actions UI by upgrading all actions from @v3 to @v4

appendices/vulkanscdeviations.adoc, chapters/fundamentals.adoc
clarifying that UTF-8 strings returned from queries in fixed-length buffers will always include the null terminator in that buffer.
Closes #2351
=> Add a <<fundamentals-strings, String Representation>> section 

appendices/VK_EXT_load_store_op_none.adoc, appendices/VK_KHR_load_store_op_none.adoc
=> Clarify that the KHR and EXT load_store_op_none extensions were not promoted to Vulkan 1.3

registry.adoc, xml/registry.rnc, xml/vk.xml
For more consistency with handling other enums type= attributes.
This is purely additive to the schema but it is conceivable that downstream scripts would look for this attribute *not* being present to indicate compile-time constants, so this should be checked against CTS / VVL / Vulkan-Hpp binding / Rust binding usage.
Closes #2359
=> Add a "constants" type= attribute to <enums> tags

registry.adoc, xml/registry.rnc, xml/vk.xml
Initially this PR only updates the XML schema and vk.xml. For the moment, the 'number' attribute is simply deprecated, but still required, until we can verify downstream repos are not affected.
The generator scripts will need to be modified to do a topological sort on the dependencies, and downstream repositories such as validation layers and Vulkan-Hpp will need to be updated to remove or replace their usage of the old attribute.
Closes #2327
=> Replace <feature number> attribute with <feature depends>

chapters/VK_GOOGLE_display_timing/queries.adoc
The current wording about `VK_PRESENT_MODE_FIFO_RELAXED_KHR` made no sense. Fixed it up to match the actual behaviour of this presentation mode.
=> Display Timing Queries: Clarify behaviour of VK_PRESENT_MODE_FIFO_RELAXED_KHR

scripts/find_equivalent_ext_require_blocks.py, xml/vk.xml
Addresses #2404
Merges extension require blocks that have identical children, extending the depends attribute with a logical or.
=> Merge equivalent require blocks

xml/vk.xml
@oddhack  As per https://github.com/KhronosGroup/Vulkan-Docs/pull/2414#issuecomment-2301342743, here's the required extension reserve PR. I have no preference on the number, I can wait until https://github.com/KhronosGroup/Vulkan-Docs/pull/2410 reserves 603 and I can reserve 604. If having this PR in the internal end makes things easier for you, let me know and I will do so!
=> Reserve extension 603

registry.adoc
all defined attributes and tags, and refer to it for sortorder and protect attributes
Closes #2395
=> Add discussion of processing frameworks being responsible for

chapters/pipelines.adoc, xml/vk.xml
=> Missing require for pipeline binary key size - #2422

registry.adoc, xml/registry.rnc, xml/vk.xml
in both command `param` and structure `member` tags.
Closes #2435
=> Support the `stride` attribute for array pointers

appendices/VK_AMDX_shader_enqueue.adoc, appendices/spirvenv.adoc, chapters/commonvalidity/dispatch_graph_common.adoc, chapters/executiongraphs.adoc, chapters/features.adoc, chapters/limits.adoc, chapters/pipelines.adoc, proposals/VK_AMDX_shader_enqueue.adoc, xml/vk.xml
- Adds mesh shader node support
- Adds two new limits to workgroups
- Variable scratch size support
=> Update VK_AMDX_shader_enqueue to v2

appendices/memorymodel.adoc
We are currently [discussing a problem](https://github.com/KhronosGroup/Vulkan-MemoryModel/issues/36) and a [potential fix](https://github.com/KhronosGroup/Vulkan-MemoryModel/pull/37) with the members of the Memory Model TSG. If the fix gets accepted, the specification also needs to be updated to reflect this change.
=> Add location order to the definition of from-reads

xml/vk.xml
We'd like to reserve the `SHADY` author ID, for supporting in-development experimental SPIR-V extensions related to the https://github.com/shady-gang/shady compiler tool chain.
I didn't find any changes in the generated headers.
=> Add SHADY author id

ChangeLog.adoc, Makefile, antora/features/modules/features/nav.adoc, appendices/spirvenv.adoc, chapters/VK_KHR_swapchain/wsi.adoc, chapters/copies.adoc, chapters/descriptorsets.adoc, chapters/initialization.adoc, chapters/limits.adoc, chapters/primsrast.adoc, chapters/resources.adoc, chapters/shaders.adoc, proposals/VK_EXT_descriptor_buffer.adoc, proposals/VK_EXT_mesh_shader.adoc, proposals/VK_KHR_pipeline_binary.adoc
Will allow validusage.json to contain mappings from VUIDs to the docs.vulkan.org page containing them.
Also adds some missing explicit anchors, and titles on deeply nested anchors.
Pairs with https://github.com/KhronosGroup/Vulkan-Site/pull/93 . Both PRs must be merged to allow building of the site to continue working - merging just one will cause problems.
=> Migrate Antora makefile targets into top-level Makefile

xml/vk.xml
This matches my OpenXR vendor ID, following the steps documented at https://registry.khronos.org/vulkan/specs/1.3/styleguide.html#extensions-naming-author-IDs
My OpenXR API layer XR_APILAYER_FREDEMMOTT_OpenKneeboard requires a matching Vulkan API layer to enable certain Vulkan extensions in `vkCreateDevice` when the OpenXR application uses the `XR_KHR_vulkan_enable` extension instead of the `XR_KHR_vulkan_enable2` - see:
- [KHR:openxr/openxr#1249](https://gitlab.khronos.org/openxr/openxr/-/issues/1249)
- [KHR:openxr/openxr#1363](https://gitlab.khronos.org/openxr/openxr/-/issues/1363) for reasons why I want to support `XR_KHR_vulkan_enable` as well as `XR_KHR_vulkan_enable2`, introducing the need for a Vulkan API layer
- https://github.com/KhronosGroup/OpenXR-SDK-Source/pull/319
=> Add author ID FREDEMMOTT

proposals/VK_EXT_external_memory_metal.adoc
This PR removes a seemingly random link to `VK_KHR_external_memory` in the proposal for `VK_EXT_external_memory_metal`.
=> Remove rogue link in VK_EXT_external_memory_metal chapter

proposals/VK_KHR_compute_shader_derivatives.adoc
This PR fixes a small typo in the proposal for the  `VK_KHR_compute_shader_derivatives` extension.
=> Fix small typo in proposal for VK_KHR_compute_shader_derivatives

appendices/VK_NV_optical_flow.adoc
Remove extra semicolon in example.
=> Remove superfluous semicolon in `VK_NV_optical_flow`

appendices/VK_HUAWEI_cluster_culling_shader.adoc, chapters/pipelines.adoc
A tiny typo fix to Pipelines article.
When I was trying to find the string I also found that same typo was present in appendices/VK_HUAWEI_cluster_culling_shader.adoc.
=> Replace fetches with fetch

xml/vk.xml
=> Fix promoted extension dependencies in vk.xml

chapters/interfaces.adoc
- Remove VUID 07037 that wrongly was needing the builtin to be of type array
- Updated the VUID 7036 to make the type a boolean value
Fixes bug https://gitlab.khronos.org/vulkan/vulkan/-/issues/3296
=> Fix the CullPrimitiveEXT VUID's

appendices/spirvenv.adoc
Add a new VUID for a relaxed control barrier with non-zero storage class semantics. PR in SPIRV-Tools:
https://github.com/KhronosGroup/SPIRV-Tools/pull/5984
=> Add VUID for relaxed control barrier with storage class semantics

ChangeLog.adoc, chapters/cmdbuffers.adoc, chapters/commonvalidity/draw_common.adoc, chapters/descriptorsets.adoc, chapters/device_generated_commands/generation.adoc, chapters/pipelines.adoc, chapters/resources.adoc
And a question about `identically defined` in [issue : pipeline layout compatibility question](https://github.com/KhronosGroup/Vulkan-Docs/issues/1853#issuecomment-2717067439)
=> All _identically defined_ link to glossary-identically-defined

chapters/textures.adoc
https://registry.khronos.org/vulkan/specs/latest/html/vkspec.html#textures-texel-replacement
> <del>If </del>If the robustImageAccess2 feature is enabled, zero values must be returned. If only the sample index was invalid, the values returned are undefined.
I think this is the correct fix.
=> Fix "If If" in Texel Replacement section

chapters/VK_INTEL_performance_query/queries.adoc
`data.` is unnecessary, documents for other unions do not contain such prefix either.
=> Fix union member name markup

antora/spec/modules/ROOT/pages/index.adoc
This PR is a first attempt to rework and expand the landing page for the Antora based Vulkan docs site.
The goal behind this is to give people some guidance on what the docs site contains, how to navigate it and how to get started with Vulkan.
In short: Make the docs site a bit more welcoming and help people find their way around ;)
This was something we discussded during multiple internal calls.
A rendered preview can be found at https://gpuinfo.org/misc/docsite/site/spec/latest/index.html (Please ignore missing links and meta data, this is not a full build of the site).
Current landing page for comparison: https://docs.vulkan.org/spec/latest/index.html
=> Rework and expand docs site landing page

chapters/shaders.adoc
This (totally minor) PR removes a superfluous underscore in the compute shader paragraph in the shaders chapter:
=> Remove superfluous underscore in shaders chapter

chapters/interfaces.adoc
Make clear that the variable contains coordinates of a local workgrroup, not "the global workgroup", and tighten up the definition of the range.
Fixes #2538
=> Clarify WorkgroupId definition

proposals/VK_QCOM_tile_shading.adoc
- Fix a bunch of typos
- Fix broken links with erroneous `.html` in the anchor
=> Clean up `VK_QCOM_tile_shading.adoc` proposal
